README.md

Forward port documentation update from edifice to garden.

Forward port edifice -> garden

---

src/ArduPilotPlugin.cc

Forward port: edifice branch to garden
- Ensure the model base link is set the correct model

Edifice ➡️  Garden

---

.gitignore
src/ArduPilotPlugin.cc

* Review unused headers
* Fix comment re: Ignition Gazebo frame conventions
* Use local imuMsg

Small fixes: remove unused headers, fix comment, more

---

README.md

This PR updates the README for the Ignition Edifice version of the plugin.
It is a back-port of the updated README for the Ignition Fortress version (i.e. Fortress -> Edifice and links updated)

Update README (back-port from readme for Fortress)

---

README.md

Fix the aspect ratio of the images in the model gallery on mobile devices.

Fix model image aspect ratio in README

---

models/iris_with_standoffs/model.sdf

Update the materials in the Iris to use physically based rendering.

Iris: update materials to use PBR

---

models/iris_with_standoffs/model.sdf

Forward port #70 to `ros2` branch.

Iris: forward port #70 to ros2

---

models/iris_with_ardupilot/model.sdf
models/iris_with_gimbal/model.sdf
models/zephyr_with_ardupilot/model.sdf
models/zephyr_with_parachute/model.sdf

Forward port #73 to `ros2` branch.

Models: forward port #73 to ros2

---

models/gimbal_small_1d/model.sdf
models/gimbal_small_2d/model.sdf
models/iris_with_ardupilot/model.sdf
models/iris_with_gimbal/model.sdf
models/iris_with_standoffs/model.sdf
models/parachute_small/model.sdf
models/runway/model.sdf
models/zephyr/model.sdf
models/zephyr_with_ardupilot/model.sdf
models/zephyr_with_parachute/model.sdf
tests/worlds/test_anemometer.sdf
tests/worlds/test_gimbal.sdf
tests/worlds/test_parachute.sdf
worlds/iris_runway.sdf
worlds/iris_warehouse.sdf
worlds/zephyr_parachute.sdf
worlds/zephyr_runway.sdf

Forward port #68 to `ros2` branch.

Models: forward port #68 to ros2

---

src/CameraZoomPlugin.cc

Camera: forward port #79 to ros2

---

models/runway/model.sdf

Forward port of #85. 
Sorry, I forgot to do it to both branches.

Runway: fix render order issue causing vehicle model to be hidden

---

.github/workflows/ccpcheck.yml
.github/workflows/ccplint.yml
.github/workflows/ubuntu-build.yml

https://github.com/ArduPilot/ardupilot_gazebo/pull/93 breaks CI as the build expects harmonic as default.

Switch CI to use gz-harmonic

---

src/ArduPilotPlugin.cc
src/CameraZoomPlugin.cc
src/GstCameraPlugin.cc
src/ParachutePlugin.cc
src/Util.cc

Add missing includes required by linter.

CI: resolve missing includes for cpplint

---

package.xml

Add gstreamer build dependencies to packages.xml.

ROS: add gstreamer deps to package.xml

---

README.md
config/gazebo-iris-gimbal.parm

Port #104 to ros2

---

package.xml

Port #118 to ros2

---

.github/workflows/ubuntu-build.yml

Replace discontinued version of cache action.

CI: update actions/cache to v4

---

.github/workflows/ubuntu-build.yml

Apply https://github.com/ArduPilot/ardupilot_gazebo/pull/135 to `ros2` branch

CI: ros2: update actions/cache to v4

---

CMakeLists.txt
README.md
package.xml

Update build and README to support the most recent version of Gazebo: [Gazebo Ionic](https://gazebosim.org/docs/latest/install/)

Gazebo: support Gazebo Ionic

---

CMakeLists.txt
README.md
package.xml

Apply https://github.com/ArduPilot/ardupilot_gazebo/pull/134 to `ros2` branch.

Gazebo: ros2: support Gazebo Ionic

---

src/ArduPilotPlugin.cc

Suppress all servo output for a channel when the input pwm is 0.
This addresses a problem that for many non-standard vehicles with custom servo mappings, ArduPilot SITL will send pwm=1000 (or sometimes pwm=1500) while the vehicle is initialising. If these values do not correspond to the pwm level for motor off or a neutral servo position, the vehicle will move while initialising.
The approach is to place a check on each servo channel that the pwm is not zero. If the pwm is zero a flag is set marking the output as not ready, and the motor output function skips that channel's output, whether forwarding to another controller or for handling in the ArduPilot plugin.
The change is backwards compatible with existing SITL code, and requires an upstream change to `AP_HAL_SITL/SITL_State.cpp` to …

ArduPilotPlugin: add check that servos are ready for output
