ArduPilot/ardupilot_gazebo

- src/ArduPilotPlugin.cc
This PR fixes a bug where the base model link associated with the `ArduPilotPlugin` may be incorrectly associated with the wrong model, leading to an incorrect pose being published. The issue is apparent in multi-vehicle simulations.  
The fix is to ensure that the link is set in the same `if` clause as the IMU topic.
**Before fix**
When running a multi-vehicle simulation, some vehicles will report incorrect position leading to poor EFK status and a loss of control of the vehicle in controlled modes.
**After fix**
All vehicles will report the correct position and expected EKF status. Tested with a 3-Iris quadcopter configuration.
> Ensure the model base link is set to the correct model

- include/ArduPilotPlugin.hh
- src/ArduPilotPlugin.cc
This PR authored by @[clydemcqueen](https://github.com/clydemcqueen)  adds a new control type `COMMAND` that forwards a command value calculated from the SITL PWM inputs to an ignition transport topic. The published command is expected to be processed by another plugin that will apply the command to the joint / joints for which it is responsible. An immediate application is to supply commands to the `ignition-gazebo` thruster system plugin for use with an ROV controlled by ArduSub. 
Example: to use the new control type on channel 0:
```xml
<control channel="0">
<jointName>thruster1_joint</jointName>
<servo_min>1100</servo_min>
<servo_max>1900</servo_max>
<type>COMMAND</type>
<cmd_topic>/model/bluerov2/joint/thruster1_joint/cmd_thrust</cmd_topic>
<offset>-0.5</offset> …
```
> Add COMMAND control type

- .github/workflows/ccpcheck.yml
- .github/workflows/ccplint.yml
- CPPLINT.cfg
- README.md
- include/ArduCopterIRLockPlugin.hh
- include/ArduPilotPlugin.hh
- include/GimbalSmall2dPlugin.hh
- include/SelectionBuffer.hh
- include/Socket.h
- src/ArduCopterIRLockPlugin.cc
- src/ArduPilotPlugin.cc
- src/GimbalSmall2dPlugin.cc
- src/Socket.cpp
This PR adds workflows for static checks using [cpplint](https://github.com/cpplint/cpplint) and [cppcheck]().
The style enforced is largely that outlined in the [Google Style Guide](https://github.com/google/styleguide) with filters to allow the style modifications described in the [Gazebo style guide](https://gazebosim.org/docs/garden/contributing#style-guides).
> Add workflow for static checks

- CMakeLists.txt
- include/Util.hh
- models/iris_with_ardupilot/model.config
- models/iris_with_ardupilot/model.sdf
- models/iris_with_standoffs/model.config
- models/iris_with_standoffs/model.sdf
- src/ArduPilotPlugin.cc
- src/Util.cc
- worlds/iris_arducopter_runway.world
This PR adds support for nested models. This feature was available in the original version of the plugin for Gazebo11.
- Fixes #6
- Supersedes #8.
Ensure methods to find links, joints and sensors search in nested models.
This change will permit more complex models containing sensors and other peripherals to be composed from a collection of simpler models.
- Add a custom version of `Model::JointByName`.
- Search for entities given a scoped name and then check that those found support the required components (`Joint` and `JointVelocity`).
- In the `ApplyForce` function add a check that the `JointVelocity` and `JointPosition` components are valid before dereferencing them.
- Rewrite the search for the IMU sensor component to use scoped names ensuring backwards compatibility.
- Update the …
> Add support for nested models

- models/zephyr_with_ardupilot/model.sdf
Closes #22 
**Issue details**
**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x ] Plane
[  ] Rover
[  ] Submarine
**Airframe type**
- Flying wing
**Hardware type**
- Gazebo / SITL
- Servos directions for the zephyr in the ardupilot_plugin parameters are reversed.
- Changed multiplier in zephyr sdf
- Update parameters description zephyr sdf
Tested on zephyr with ardupilot 4.1.7
> Fix servo reverse related issue.

- include/ArduPilotPlugin.hh
- src/ArduPilotPlugin.cc
This PR adds support for up to six range sensors.
**Edit: 16 Dec 2022**
*Rebase PR onto `main` and update to incorporate migration from ign -> gz*.
Why only six? The `SITL_JSON` interface accepts data from up to six range sensors. ArduPilot will support up to ten, but the number of fields in `SITL_JSON` is currently six and we do not propose an upstream change at this point. 
[The sonar sensor type from Gazebo Classic has not yet been ported to Gazebo Sim](https://github.com/ignitionrobotics/ign-sensors/issues/19), however we can approximate a sonar sensor using a Lidar sensor as an interim solution.
The sensor is added to a sdf `<link>` element. For example:
```xml
<sensor name='sonar' type='gpu_lidar'>
<always_on>1</always_on>
<update_rate>20</update_rate>
<visualize>1</visualize> …
```
> Add support for range sensors

- README.md
Add a section containing examples of models configured for use with ArduPilot SITL and provide links to the documents in [ArduPilot/SITL_Models](https://github.com/ArduPilot/SITL_Models).
The document uses HTML for the image gallery as plain markdown does not format well.
> Add Models section to README

- include/ArduPilotPlugin.hh
- models/iris_with_ardupilot/model.sdf
- src/ArduPilotPlugin.cc
Enable 32 servos when the parameter SERVO_32_ENABLE is set.
This PR is the companion to https://github.com/ArduPilot/ardupilot/pull/23239 for the ArduPilot gazebo plugin.
- Add optional boolean plugin parameter `<have_32_channels>` to enable 32 rather than 16 channels.
- Add new struct for the servo packet with 32 channels and new magic number matching SITL_JSON.
- Modify UpdateMotor commands to accept a std::array of PWMs rather than the entire servo packet.
- Update ReceiveServoPacket to receive either 16 or 32 channel servo packet depending on the plugin parameter `<have_32_channels>`.
Testing with `iris_runway.sdf` world:
```bash
gz sim -v4 -r iris_runway.sdf
```
```bash
sim_vehicle.py -D -v ArduCopter -f gazebo-iris --model JSON  --console
```
Enable 32 servos in MAVProxy:
Magic …
> Enable 32 servos

- include/ArduPilotPlugin.hh
- src/ArduPilotPlugin.cc
- tests/worlds/test_anemometer.sdf
Add support for an anemometer sensor.
The existing SITL-JSON schema includes a `windVane` element that expects the apparent wind speed and direction.
The direction is the angle radians from the forward direction using the FRD frame convention. Angles should be in the range [-PI, PI]. The speed is measured in m/s.
```javascript
windVane {
direction: 0.0,
speed: 0.0 
}
```
Populating `windVane` data is enabled by including an `<anemometer>` element in the plugin definition. The element should contain the scoped name of an anemometer sensor. For example:
```xml
<plugin name="ArduPilotPlugin"
filename="ArduPilotPlugin">
<fdm_addr>127.0.0.1</fdm_addr>
<fdm_port_in>9002</fdm_port_in>
<connectionTimeoutMaxCount>5</connectionTimeoutMaxCount>
<lock_step>1</lock_step> …
```
> Anemometer: add wind sensor

- CMakeLists.txt
- hooks/ardupilot_gazebo.dsv.in
- hooks/ardupilot_gazebo.sh.in
- package.xml
Allow `ardupilot_gazebo` to be built as a ROS 2 ament package if the ament dependencies are available, otherwise default to a standalone `cmake` only build.
- Add ROS 2 `ament` package configuration.
- Build as `ament` package if possible, otherwise revert to standard `cmake` build.
- Add install section to CMakeLists.txt
- Add environment hooks to update `GZ_SIM_RESOURCE_PATH` and `GZ_SIM_SYSTEM_PLUGIN_PATH`.
> ROS: build as ament package if ROS available

- models/iris_with_ardupilot/model.sdf
- models/iris_with_gimbal/model.sdf
- models/zephyr_with_ardupilot/model.sdf
- models/zephyr_with_parachute/model.sdf
- tests/worlds/test_anemometer.sdf
- Use filename="ArduPilotPlugin" rather than filename="libArduPilotPlugin".
Tested iris and zephyr models with ArduPilot [master: d3f2309](https://github.com/ArduPilot/ardupilot/commit/d3f2309eac1bf522720d27b3a22c242d32e2a6cd).
> Models: drop lib prefix from plugin filename

- models/gimbal_small_1d/model.config
- models/gimbal_small_1d/model.sdf
- models/gimbal_small_2d/model.config
- models/gimbal_small_2d/model.sdf
- models/iris_with_ardupilot/model.config
- models/iris_with_ardupilot/model.sdf
- models/iris_with_gimbal/model.config
- models/iris_with_gimbal/model.sdf
- models/iris_with_standoffs/model.config
- models/iris_with_standoffs/model.sdf
- models/parachute_small/model.config
- models/parachute_small/model.sdf
- models/runway/model.config
- models/runway/model.sdf
- models/zephyr/model.config
- models/zephyr/model.sdf
- models/zephyr_with_ardupilot/model.config
- models/zephyr_with_ardupilot/model.sdf
- models/zephyr_with_parachute/model.config
- models/zephyr_with_parachute/model.sdf
- tests/worlds/test_anemometer.sdf
- tests/worlds/test_gimbal.sdf
- tests/worlds/test_nested_model.sdf
- tests/worlds/test_parachute.sdf
- worlds/iris_runway.sdf
- worlds/iris_warehouse.sdf
- worlds/zephyr_parachute.sdf
- worlds/zephyr_runway.sdf
Upgrade models to SDF version 1.9.
The [`merge`](http://sdformat.org/tutorials?tut=composition_merge_proposal&cat=pose_semantics_docs&) attribute is required to support composed models in [`sdformat_urdf`](https://github.com/ros/sdformat_urdf).
- Update to SDF version 1.9.
- Update `model.config` `<version>` number.
- Remove element `<use_parent_model_frame>`
Tested iris, iris with gimbal and zephyr models with ArduPilot [master: d3f2309](https://github.com/ArduPilot/ardupilot/commit/d3f2309eac1bf522720d27b3a22c242d32e2a6cd).
> Models: update to sdf version 1.9

- models/gimbal_small_2d/model.sdf
- models/iris_with_gimbal/model.sdf
- models/iris_with_standoffs/model.sdf
Modifications to support running ArduPilot SITL / Gazebo with ROS 2.
The `ros2` branch includes changes to make the iris model compatible with the package [sdformat_urdf](https://github.com/ros/sdformat_urdf). The package allows a SDFormat robot model to be used as a robot description by ROS tools such as RViz, however it imposes some restrictions on the model.
Changes to model structure
- The prefix `model://{model_name}` must be replaced by `package://{package_name}/models/{model_name}`.
- Nested models must use the `//model/include/@merge="true"` attribute which requires elements in included models to have unique names.
Transform fix
- An additional rotation is needed to correctly map from the Gazebo ENU world frame to the ArduPilot NED frame.
Rendering
- The rotor blades are colour …
> ROS: modify iris example to support sdformat_urdf

- models/iris_with_ardupilot/model.sdf
- models/iris_with_gimbal/model.sdf
- models/runway/model.sdf
- models/zephyr_with_ardupilot/model.sdf
- models/zephyr_with_parachute/model.sdf
- tests/worlds/test_anemometer.sdf
- tests/worlds/test_gimbal.sdf
- tests/worlds/test_parachute.sdf
- worlds/iris_runway.sdf
- worlds/zephyr_parachute.sdf
- worlds/zephyr_runway.sdf
Correct the rotation in the plugin XML element `< gazeboXYZToNED >` that maps between the world frames used in Gazebo and ArduPilot. The missing rotation is apparent when specifying the world origin geolocation with the `<spherical_coordinates>` element and using and navsat sensor.
Closes #58
- Gazebo uses the ENU convention for world frames, ArduPilot uses NED.
- Add the missing z-axis rotation to the element `< gazeboXYZToNED >`.
- Update the vehicle initial world pose so model is initially oriented north.
- Add navsat sensors and system so location may be visualised with the Gazebo NavSat GUI tool.
- Add axes models to example worlds to aid orientation.
> Models: correct transform from ENU to NED

- models/iris_with_gimbal/model.sdf
Update the odom and robot frames for the `OdometryPublisher` plugin to conform with [ROS REP 105](https://www.ros.org/reps/rep-0105.html).
- Remove the frame prefix in `<odom_frame>`.
- Change `<robot_base_frame >` to `base_link`.
Required to fix: https://github.com/ArduPilot/ardupilot_gz/issues/30
> Iris: set base_link as mobile base in odometry publisher

- CMakeLists.txt
- README.md
- package.xml
- src/ArduPilotPlugin.cc
- src/ParachutePlugin.cc
Add support for Gazebo Harmonic retaining the default support for Gazebo Garden. The version used is controlled by the environment variable `GZ_VERSION` which should be either `garden` or `harmonic`. If not set the default is to assume `garden`.
- Use the same approach for versioning used in [`ros_gz`](https://github.com/gazebosim/ros_gz).
- Update `package.xml` and `CMakeLists.txt` to handle either `garden` or `harmonic`.
- Add missing `gz-msg` headers that cause compilation to fail in Harmonic.
Tested on macOS Ventura with Harmonic built from source and running the Iris quadcopter example.
> Gazebo: support Gazebo Harmonic and Garden

- models/iris_with_ardupilot/model.sdf
- models/iris_with_gimbal/model.sdf
- models/zephyr_with_ardupilot/model.sdf
- models/zephyr_with_parachute/model.sdf
The LiftDrag plugin in Gazebo Harmonic enables the moment contribution which was previously ignored. This PR sets the `<cma>` parameter to zero to ensure consistent behaviour between Gazebo Garden and Harmonic. 
- Factor the `<cma>` fix from: https://github.com/ArduPilot/ardupilot_gazebo/pull/68 i
- See also: https://github.com/gazebosim/gz-sim/pull/2189
> Models: set lift-drag moment coefficient to zero

- models/gimbal_small_1d/model.sdf
- models/gimbal_small_2d/model.sdf
- models/iris_with_ardupilot/model.sdf
- models/iris_with_gimbal/model.sdf
- models/iris_with_standoffs/model.sdf
- models/parachute_small/model.sdf
- models/zephyr/model.sdf
- models/zephyr_with_ardupilot/model.sdf
- models/zephyr_with_parachute/model.sdf
- tests/worlds/test_anemometer.sdf
- worlds/iris_runway.sdf
- worlds/iris_warehouse.sdf
- worlds/zephyr_parachute.sdf
This PR reviews and fixes the orientation of models and worlds to ensure compliance with the conventions used by ROS and ArduPilot. 
- https://discuss.ardupilot.org/t/compass-settings-compasses-inconsistent-error/110592
**Edit** `<cma>` fix below moved to #73 
There is also a fix for planes on Harmonic where a change in behaviour of the LiftDrag plugin requires the moment coefficient `<cma>` to be set to zero in order to disable the adjustment (it was previously ignored).
- https://github.com/gazebosim/gz-sim/pull/2189
- Use degrees rather than radians in `<pose>` where this simplifies or clarifies the rotation.
- Replace `-0` with `0`. These arise where the SDF model had been originally generated from URDF.
Models
Worlds
Tests
> Models: fix world orientation

- src/CameraZoomPlugin.cc
Fixes #77 
Make sure to hit Play in gazebo for the image topic to show up!
> Add protection for nulltpr crash in CameraZoomPlugin

- models/gimbal_small_3d/model.sdf
- src/CameraZoomPlugin.cc
Solves #57 , implementing a zoom slew rate to give realistic zoom effect for optical cameras like the Nikon P1000.
Add the following to your CameraZoomPlugin:
```xml
<slew_rate>0.42514285714</slew_rate>
```
The value is camera-specific and can be calculated per the issue description.
https://github.com/ArduPilot/ardupilot_gazebo/assets/25047695/eb7485e4-2eae-4162-813c-2b3eeec506eb
Depends on #79 to go in first.
* This plugin is only used with pinhole lense cameras, which I don't think is enforced.
> Zoom slew rate

- models/gimbal_small_3d/model.sdf
- src/CameraZoomPlugin.cc
> Camera: forward port #81 to ros2

- models/runway/model.sdf
Fix a render order issue that causes vehicle models to be hidden behind the runway.
See: https://community.gazebosim.org/t/graphic-artifacts-clipped-or-not-visible-drone/2510
> Runway: fix render order issue causing vehicle model to be hidden

- CMakeLists.txt
- README.md
- package.xml
Update the default to install gazebo harmonic and recommend it, and use OSRF's rosdep registry to resolve the right version of the simulator.
> Default to gazebo harmonic

- .github/workflows/ubuntu-build.yml
- CMakeLists.txt
- README.md
- include/GstCameraPlugin.hh
- models/gimbal_small_1d/model.sdf
- models/gimbal_small_2d/model.sdf
- models/gimbal_small_3d/model.sdf
- src/GstCameraPlugin.cc
I'm sure it could be improved, but here's a port of the gazebo classic GstCameraPlugin into Gazebo harmonic. This was heavily based on the plugin from the PX4 gazebo repo (https://github.com/PX4/PX4-SITL_gazebo-classic/blob/main/src/gazebo_gst_camera_plugin.cpp) and the existing camera zoom plugin. 
I ran into problem after problem trying to use the new gazebo api for taking frames from the gazebo server and ended up subscribing to the gazebo image topic instead. It works really well, but I'd love feedback or improvements for this approach as I know it's not super efficient. Hoping this PR gets the ball rolling in the right direction.
> Camera: ported GstCameraPlugin from PX4 gazebo classic

- config/gazebo-iris-gimbal.parm
- models/gimbal_small_1d/model.sdf
- models/gimbal_small_2d/model.sdf
- models/gimbal_small_3d/model.sdf
- models/iris_with_gimbal/model.sdf
- worlds/iris_runway.sdf
- worlds/iris_warehouse.sdf
Updates https://github.com/ArduPilot/ardupilot_gazebo/pull/86 which was on a `main` branch preventing maintainer edits.
- Update the gimbal model used by the Iris to 3d and add yaw control channel.
- Use the `iris_with_gimbal` model as default in example worlds.
- Reduce position controller PID gains to reduce potential oscillation.
- Update channels to match servo gimbal wiki doc: https://ardupilot.org/copter/docs/common-camera-gimbal.html
- Update servo control direction
| Action | Channel | RC Low | RC High |  Min (deg) | Max (deg) |
| --- | --- | --- | --- | --- | --- |
| Roll | RC6 | Roll Left | Roll Right | -30 | +30 |
| Pitch | RC7 | Pitch Dn | Pitch Up | -135 | +45 |
| Yaw | RC8 | Yaw Left | Yaw Right | -160 | 160 |
Copter params
```bash
FRAME_CLASS	     1
FRAME_TYPE	     1 …
```
> Iris: update iris_with_gimbal model to 3d gimbal

- .github/workflows/ubuntu-build.yml
- CMakeLists.txt
- README.md
- include/GstCameraPlugin.hh
- models/gimbal_small_1d/model.sdf
- models/gimbal_small_2d/model.sdf
- models/gimbal_small_3d/model.sdf
- src/GstCameraPlugin.cc
Port #97 to `ros2` branch.
Closes #98
> Port #97 to ros2

- README.md
- config/gazebo-iris-gimbal.parm
In reference to the [PR](https://github.com/ArduPilot/ardupilot_gazebo/pull/102) by @srmainwaring. Updated readme to setup and control gimbal over ground control.
> Gimbal: Added rc channel control readme

- CPPLINT.cfg
- include/SocketUDP.hh
- src/SocketUDP.cc
> Port #106 to ros2

- config/gazebo-iris-gimbal.parm
> Iris: remove inline comments in param file

- .github/workflows/ubuntu-build.yml
Closes #126 
This PR changes the CI to use the `setup-gazebo` GitHub Action to configure a Gazebo environment. It replaces Harmonic's installation steps and passes input to the action to take care of the installation.
> Using `setup-gazebo` GitHub Action to install Gazebo in CI

- models/gimbal_small_1d/model.sdf
- models/gimbal_small_2d/model.sdf
- models/gimbal_small_3d/model.sdf
- models/iris_with_standoffs/model.sdf
- models/zephyr/model.sdf
Adds `gz_frame_id` to camera and IMU sensor to ensure the ROS topics have the correct `frame_id`.
`gz_frame_id` is also already added in other models used with Ardupilot:
- https://github.com/ArduPilot/ardupilot_gz/pull/64
- https://github.com/ArduPilot/SITL_Models/commit/ed8a3d25b66b5200fe8585f87104cd278da90753#diff-e62fc778fd4fc8dea0507f90838bf11850f7ae06eccd773aad32324a39388252
Tested on Ubuntu 22.04, Gazebo Harmonic and ROS 2 Humble
> Add gz_frame_id's to sensors
